name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '15.x'

    - run: npm install
    - run: npm run lint
    - run: npm run prettier
    - run: npm test
    - run: npm run build
